const newline = String.fromCharCode(10)

export const NEW_APP_PROMPT = [
  "I am building this application for ReactorLab and I want its database layer to be compatible with MiniBase.",
  "",
  "Inspect the repository before making changes and preserve the application's intended behavior.",
  "",
  "MiniBase compatibility contract:",
  "",
  "1. Use PostgreSQL for persistent application data.",
  "",
  "2. The application must obtain its database connection at runtime from DATABASE_URL. Do not hardcode the database hostname, port, database name, username, password, or a connection URI anywhere in source code.",
  "",
  "3. Do not commit database credentials or real connection strings.",
  "",
  "4. Do not log DATABASE_URL, passwords, or other database credentials.",
  "",
  "5. Do not make this application responsible for provisioning its production PostgreSQL server. Do not add a production MongoDB, PostgreSQL, or MySQL container or an externally exposed database port for the application's primary production database. MiniBase manages the production database separately.",
  "",
  "6. The application will be deployed through MiniDeploy. When a MiniBase database is attached, MiniDeploy supplies the managed DATABASE_URL automatically. Do not require the operator to manually configure DATABASE_URL inside MiniDeploy while a MiniBase database is attached.",
  "",
  "7. Structure the backend so it is compatible with MiniDeploy's current MiniBase-supported deployment paths. Current first-class support is for Node.js + Express applications and supported Vite frontend + Node.js/Express backend applications. If this project needs a backend, use a compatible Node.js/Express architecture unless the existing ReactorLab deployment contract in this repository clearly provides another supported MiniBase path.",
  "",
  "8. Add a repeatable, noninteractive database migration path. In package.json provide:",
  "",
  "   \"reactorlab:migrate\": \"<migration command>\"",
  "",
  "   The migration command must use DATABASE_URL, require no interactive input, be safe to run during deployment, exit nonzero if migration fails, and never print secrets. MiniDeploy detects this script and can run npm run reactorlab:migrate in the private data network with the managed database environment for a supported attached app.",
  "",
  "9. Use parameterized queries or a PostgreSQL-compatible database library or ORM. Preserve schema constraints, indexes, uniqueness rules, and relationships in migrations.",
  "",
  "10. Startup must fail clearly if the application requires a database and DATABASE_URL is missing or invalid. Do not silently fall back to an unrelated local database in production.",
  "",
  "11. Provide a stable application health endpoint compatible with deployment health checks. Do not leak database credentials or sensitive configuration through health responses.",
  "",
  "12. Keep the application stateless outside MiniBase for persistent relational application data unless another storage requirement is explicitly part of the project.",
  "",
  "13. Add DATABASE_URL= to .env.example, but never include a real credential.",
  "",
  "14. Do not expose PostgreSQL port 5432 publicly and do not assume the database is reachable from the public internet. PostgreSQL remains private to the internal ReactorLab data network.",
  "",
  "After implementing the changes:",
  "- run the repository's relevant tests",
  "- run database-layer tests where practical",
  "- explain the schema and migration approach",
  "- identify the health endpoint",
  "- identify the reactorlab:migrate command",
  "- list the files changed",
  "- explain any remaining steps required before deployment",
  "",
  "Do not deploy anything and do not create or modify a production MiniBase database unless I explicitly request it.",
].join(newline)

export const CONVERT_APP_PROMPT = [
  "This existing application currently uses another database or persistence implementation. I want you to refactor the project so it can use ReactorLab MiniBase as its production database.",
  "",
  "First inspect the repository and identify:",
  "- the current database technology",
  "- models and entities",
  "- queries, repositories, and data-access code",
  "- indexes and uniqueness rules",
  "- relationships and references",
  "- database environment variables",
  "- startup and database initialization behavior",
  "- migration and seed behavior",
  "- tests that depend on the current database",
  "",
  "Preserve application behavior as closely as practical while converting the persistence layer to PostgreSQL.",
  "",
  "MiniBase compatibility contract:",
  "",
  "1. The converted application must use PostgreSQL for persistent application data.",
  "",
  "2. The production database connection must come only from DATABASE_URL. Do not hardcode the production database host, port, database name, username, password, or URI.",
  "",
  "3. MiniBase and MiniDeploy manage the production connection. When a MiniBase database is attached, MiniDeploy injects DATABASE_URL automatically. Do not require DATABASE_URL to be manually entered into MiniDeploy while the attachment is active.",
  "",
  "4. Remove the application's runtime dependency on its previous primary database technology where that dependency is being replaced, such as MongoDB, MySQL, SQLite, or another externally managed database. Do not delete or destroy existing production data or automatically destroy the old database or service.",
  "",
  "5. Convert the data model carefully to relational PostgreSQL semantics. Preserve identifiers, uniqueness constraints, required and optional fields, timestamps, indexes, relationships, and application-visible behavior where applicable. When converting a document database, design appropriate tables and relations instead of blindly putting everything in one JSON column unless that is genuinely the correct model.",
  "",
  "6. Use parameterized queries or a PostgreSQL-compatible database library or ORM.",
  "",
  "7. Create a repeatable, noninteractive migration path. In package.json provide:",
  "",
  "   \"reactorlab:migrate\": \"<migration command>\"",
  "",
  "   This command must use DATABASE_URL, apply required schema migrations, require no interactive input, exit nonzero on failure, and never print secrets. MiniDeploy detects this script and can run npm run reactorlab:migrate in the private data network with the managed database environment for a supported attached app.",
  "",
  "8. Do not log DATABASE_URL or credentials.",
  "",
  "9. Do not commit credentials or real connection strings.",
  "",
  "10. Do not add a separately managed production PostgreSQL container for this application's primary database. MiniBase manages PostgreSQL.",
  "",
  "11. Do not expose PostgreSQL port 5432 publicly or assume the database is reachable from the public internet. PostgreSQL remains private to the internal ReactorLab data network.",
  "",
  "12. Ensure the backend fits a MiniDeploy path that currently supports MiniBase. Current first-class MiniBase attachment support is Node.js + Express and supported Vite frontend + Node.js/Express backend applications. If the existing backend is incompatible, refactor only what is necessary to make a MiniBase-compatible version while preserving externally visible behavior.",
  "",
  "13. Startup must fail clearly if the application requires its database and DATABASE_URL is missing or unusable.",
  "",
  "14. Provide or preserve a stable deployment health endpoint. Health output must not expose credentials.",
  "",
  "15. Add DATABASE_URL= to .env.example or equivalent example configuration without a real secret.",
  "",
  "16. If real data must be migrated from the previous database into PostgreSQL, do not perform a destructive migration automatically and do not delete the old data. Provide a separate migration or import plan or script, and require explicit operator approval for destructive or irreversible steps.",
  "",
  "After the refactor:",
  "- run the relevant tests",
  "- add or update persistence tests where practical",
  "- explain how the old data model maps to PostgreSQL",
  "- identify the migration command",
  "- identify the health endpoint",
  "- identify obsolete database environment variables and dependencies",
  "- list the files changed",
  "- explain any manual data-migration step separately",
  "",
  "Do not deploy the application and do not mutate a production MiniBase database unless I explicitly request it.",
].join(newline)
